device:
  host: 192.168.18.106
  port: 4370
endpoint: http://test.com # don't forget to point this to your application route
transmission: true
log:
  filename: transactions # do not include extension
  split: true
